### ISSUE TITLE
Display the updated expiry version for histograms that were updated

### ISSUE THREAD

**Issue by Dexterp37** [mozilla/probe-dictionary#41]
The expiration for the [`WEBEXT_BACKGROUND_PAGE_LOAD_MS`](https://searchfox.org/mozilla-central/source/toolkit/components/telemetry/Histograms.json#13368) probe was extended to `67` on May 2.
However, [its entry](https://telemetry.mozilla.org/probe-dictionary/?search=webext&detailView=histogram%2FWEBEXT_BACKGROUND_PAGE_LOAD_MS) in the probe dictionary still reports a recorded in versions "nightly 55 to 62" instead of "nightly 55 to 67".

**Comment by Dexterp37** [comment]
Please note that [the data](https://probeinfo.telemetry.mozilla.org/firefox/all/main/all_probes) from the scraper looks correct.

**Comment by chutten** [comment]
This may be intended behaviour as the probe dictionary checks https://probeinfo.telemetry.mozilla.org/firefox/revisions to see which revisions are presently valid and uses that to determine its ranges.

Thus, since we (as of yet) have no Nightly beyond 62, maybe this is expected?

If so, :S (this has now confused at least three people)

**Comment by georgf** [comment]
This doesn't seem to do what people expected.
We should show the "expiry" version on the channel instead of the "last seen in" version.

**Comment by chutten** [comment]
Or maybe both, if "last seen in" has more informational value than just "min(expiry - 1, current_version_for_channel)"?

**Comment by georgf** [comment]
I think from the users perspective, what mostly matters is:
- If the probe is still recorded, from when on? If it has an expiry, from when until when?
- If the probe is not recorded anymore, from when to when was it recorded?

The reason why it is not recorded anymore (probe removed or expired) seems secondary and we could follow up on that later.

**Comment by Dexterp37** [comment]
Ok, one part of this problem was #44. I'm addressing it.

**Comment by Dexterp37** [comment]
I propose to slightly change the UI for probes that are still recorded as shown in the picture below:

![proposal_probe_dictionary](https://user-images.githubusercontent.com/883721/41653302-ea9cc164-7485-11e8-9a1b-3103eb8f41d1.PNG)

For probes that are not recorded any-more, the UI should basically stay the same.

@chutten @georgf  what's your take on this? This is likely to wait for Georg to come back, so no rush.

**Comment by chutten** [comment]
Should use the future tense "expires in" instead of "expired in" for something in the future. Could also use "until" for extra brevity.

Aside from grammatical quibbles, this opens up the continual problem of how to clearly denote which version we start forbidding probes from being recorded. "Expires in" "Last recorded in"...

Maybe we should use the "from 54" language we use for non-expiring probes? ...though when a probe is expiring is crucial information, I guess... and when the channel is "any" a probe could be simultaneously recorded and expired :S

Bleh. Go with "until" and force people to click into the detail view to see what it actually means.

**Comment by chutten** [comment]
[`<abbr>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/abbr) has a `title` attribute that'll throw out a tooltip if you hover over it with a pointer. AFAICT it also has reasonable support by screen readers. Maybe we can use that in conjunction with "until" to be clear about whether it does or does not record in that version.

```html
<abbr title="up to but not including">until</abbr> 65
```

**Comment by georgf** [comment]
I'd say we should keep the information in the search summary results as simple as possible.

If we can limit this to "from V" and "V1 to V2", that would be great.
I agree that it's probably enough to put the probe expiry into the detail page.

So we would end up with:
- "from V" for any probe that has not expired yet
- "V1 to V2" for any probe that already expired

**Comment by georgf** [comment]
One question though:
Is there a problem with the way it's currently shown?

**Comment by chutten** [comment]
Well, right now all of these probes are listed as recorded up to 61: https://telemetry.mozilla.org/probe-dictionary/?search=webext

This is untrue, as nightly is recording at least one of them 63: https://telemetry.mozilla.org/probe-dictionary/?search=webext&detailView=histogram%2FWEBEXT_BACKGROUND_PAGE_LOAD_MS

Regardless of wording, we have a communication issue here.

**Comment by georgf** [comment]
Ah!
That seems like a bug [here](https://github.com/mozilla/probe-dictionary/blob/a4d7db8bc2e09bf4903bc1a845e1c8c642ea5d9c/explore.js#L468) in how we show probe recording ranges for probes that have an expiry set.

I think we just need to change that into:
```
if ((lastVersion >= expiryVersion) || (lastVersion >= latestVersion)) {
  ...
```
