### ISSUE TITLE
Modernize the front-end code

### ISSUE THREAD

**Issue by georgf** [mozilla/probe-dictionary#5]
Currently the front-end code here uses plain JS + some jquery.
We should use a more modern frame-work (Angular, React, Vue).

**Comment by georgf** [comment]
I checked with our data tools people: react + redux is what we mostly standardized on at Mozilla.

**Comment by hampgoodwin** [comment]
I'm working out what would be a good standard practice for moving an existing project into react compared against creating a new project. I'll be doing some reading/research and practice before getting this issue started. This issue is also a pre-cursor to other issues so I'll focus on this for now.

**Comment by georgf** [comment]
Great, cheers.
Let me know if there are open questions - we can probably loop in someone from our data tools team to help & review.
